#!/usr/bin/ash

run_hook ()
{
  echo "Starting tinyssh"
  /usr/bin/xinetd -filelog /var/log/xinetd.log -pidfile /var/run/xinetd.pid
}

run_cleanuphook ()
{
    if [ -f /var/run/xinetd.pid ]; then
        kill `cat /var/run/xinetd.pid`
    fi
}
