#!/usr/bin/ash

run_hook ()
{
  [ -d /dev/pts ] || mkdir -p /dev/pts
  mount -t devpts devpts /dev/pts

  echo "Starting tinyssh"
  /usr/bin/xinetd -filelog /var/log/xinetd.log -pidfile /var/run/xinetd.pid
}

run_cleanuphook ()
{
    umount /dev/pts
    rm -R /dev/pts
    if [ -f /var/run/xinetd.pid ]; then
        kill `cat /var/run/xinetd.pid`
    fi
}
