#!/bin/bash

display_fingerprints() {
  if [ -d /etc/tinyssh/sshkeydir ]; then
      tinysshd-printkey /etc/tinyssh/sshkeydir
  fi
}

generate_keys() {
  if [ ! -d /etc/tinyssh/sshkeydir ]; then
      tinysshd-makekey /etc/tinyssh/sshkeydir
  fi
}

create_systemd_customdep () {
    add_dir "/etc/systemd/system/tinyssh@22.socket.d"
    cat << CUSTOMEOF > "${BUILDROOT}/etc/systemd/system/tinyssh@22.socket.d/cryptsetup-dep.conf"
[Unit]
Before=
Before=cryptsetup.target
CUSTOMEOF
}

build ()
{
  #
  # Begin real processing
  #

  # Are we even needed?
  if [ ! -r "/etc/tinyssh/root_key" -o ! -s "/etc/tinyssh/root_key" ]; then
    echo "There is no root key in /etc/tinyssh/root_key existent; exit"
    return 0
  fi

  # if TMPDIR is set leave it alone otherwise set
  [ -z $TMPDIR ] && TMPDIR='/tmp/mkinitcpio-tinyssh'

  # check if TMPDIR exsists if not make it
  [ -d $TMPDIR ] || mkdir -p $TMPDIR

  umask 0022

  generate_keys
  display_fingerprints

  #systemd enabled
  declare -F add_systemd_unit > /dev/null 2>&1
  if [ $? -eq 0 ]; then
      add_systemd_unit "tinysshgenkeys.service"
      add_systemd_unit "tinyssh@.socket"
      add_systemd_unit "tinyssh@.service"
      systemctl --root "$BUILDROOT" enable tinyssh@22.socket
      create_systemd_customdep
  #base enabled
  else
      add_checked_modules "/drivers/net/"
      add_binary "rm"
      add_binary "killall"
      add_binary "tinysshd"
      add_binary "tcpserver"
      add_file "/lib/libnss_files.so.2"
      add_runscript
  fi

  #both
  add_dir "/root/.ssh"
  cat /etc/tinyssh/root_key > "${BUILDROOT}"/root/.ssh/authorized_keys

  #necessary for tinyssh private keys
  shopt -s dotglob
  add_full_dir "/etc/tinyssh"
  shopt -u dotglob

}

help ()
{
    cat<<HELPEOF
This hook is meant to be used in conjunction with mkinitcpio-netconf and/or
mkinitcpio-ppp. It DOES NOT provide any default shell. It will only install
and start tinyssh on early userspace. In the package mkinitcpio-utils you
will find hooks and shells for remote unlocking a luks root partition,
among others.
HELPEOF
}
