#!/usr/bin/ash

run_hook ()
{
  [ -d /dev/pts ] || mkdir -p /dev/pts
  mount -t devpts devpts /dev/pts

  echo "Starting tinyssh"
  /bin/tcpsvd 0 22 /usr/sbin/tinysshd -v /etc/tinyssh/sshkeydir
}

run_cleanuphook ()
{
    umount /dev/pts
    rm -R /dev/pts
    killall tcpsvd
}
